### ISSUE TITLE
Handling high resolution images in pdf when converted to PIL.Image (DPI=200)

### ISSUE THREAD

**Issue by rushabh-wadkar** [pypdfium2-team/pypdfium2#141]
Hi Team,

I am finding some issue with memory when dealing with high resolution images scanned in pdf. How do we appropriately handle it for DPI 200?
Requirement: We need an array of PIL.Images from converted pdf. We need DPI to be set to 200 only

Code:
```python
@profile
def test_pdfium():
    pdf = pdfium.PdfDocument(pdf_PATH)
    version = pdf.get_version()  # get the PDF standard version
    n_pages = len(pdf)  # get the number of pages in the document
    img_list = []
    for page_number in range(n_pages):
        page = pdf.get_page(page_number)
        pil_image = page.render_topil(
            optimise_mode=pdfium.OptimiseMode.NONE,
            scale=200/72
        )
        img_list.append(pil_image)
    print(img_list)
test_pdfium()
```
Output:
```
[<PIL.Image.Image image mode=RGB size=6622x8673 at 0x10BD10AC0>, <PIL.Image.Image image mode=RGB size=6447x8356 at 0x10BD10A90>, <PIL.Image.Image image mode=RGB size=6556x8628 at 0x10BD10310>]
Filename: /Users/rushabhwadkar/Desktop/Training/pdfissue/server.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     7     23.6 MiB     23.6 MiB           1   @profile
     8                                         def test_pdfium():
     9     23.8 MiB      0.2 MiB           1       pdf = pdfium.PdfDocument(pdf_PATH)
    10     23.8 MiB      0.0 MiB           1       version = pdf.get_version()  # get the PDF standard version
    11     23.8 MiB      0.0 MiB           1       n_pages = len(pdf)  # get the number of pages in the document
    12     23.8 MiB      0.0 MiB           1       img_list = []
    13    707.8 MiB      0.0 MiB           4       for page_number in range(n_pages):
    14    476.6 MiB      0.2 MiB           3           page = pdf.get_page(page_number)
    15    707.8 MiB    683.8 MiB           6           pil_image = page.render_topil(
    16    476.6 MiB      0.0 MiB           3               optimise_mode=pdfium.OptimiseMode.NONE,
    17    476.6 MiB      0.0 MiB           3               scale=200/72
    18                                                 )
    19    707.8 MiB      0.0 MiB           3           img_list.append(pil_image)
    20                                                 # pil_image.save(f"image_{page_number+1}.png")
    21    707.8 MiB      0.0 MiB           1       print(img_list)
```

If you check the memory profiler from **page.render_topil** function call, it reaches around 700MiB. Is there a way where we can appropriately handle this i.e to bring that down ?
The above scenario uses CPU and Memory which either kills our k8s pods or restarts it again-and-again!

**Comment by mara004** [comment]
I think the reason is that you are storing all images in a list. If all page rasterisations exist in memory in parallel, this is bound to lead to high memory usage, especially with longer PDFs and/or higher resolution.
`render_topil()` is a generator function, so if you just iterate through it, there should be no problem regarding memory usage.

I've had a lengthy conversation with the `doctr` folks about this topic here: https://github.com/mindee/doctr/discussions/1000

**Comment by mara004** [comment]
Hmm, perhaps this is not the only reason, though. I think, at least with the current codebase in `main`, there might be a memory leak related to rendering somewhere. I need to give this more scrutiny.

**Comment by mara004** [comment]
Please let me know if removing the `img_list` and using a generator instead (`yield` expression) fixes your memory issue.
If not, we need to investigate further.

That said, your report indicates the issue is limited to particular documents with high-resolution scanned images. Could you share an example? The image size shown in the output suggests very large pages, so you might want to use lower resolution anyway.

**Comment by mara004** [comment]
Considering your output
```
[<PIL.Image.Image image mode=RGB size=6622x8673 at 0x10BD10AC0>, <PIL.Image.Image image mode=RGB size=6447x8356 at 0x10BD10A90>, <PIL.Image.Image image mode=RGB size=6556x8628 at 0x10BD10310>]
```
we can calculate the amount of memory required for the pixel data of these three images
```python
>>> (6622 * 8673 * 3) + (6447 * 8356 * 3) + (6556 * 8628 * 3)
503606718
```
That's a bit more than 500 MB. Considering that Python, loaded libraries and their objects also take some memory, your level of memory usage is quite plausible. On your sample, using a generator should notably reduce memory usage.

**Comment by mara004** [comment]
For the record: As this is about exceptionally large pages, note that you can also implement measures to smartly absorb that as an embedder. Like defining a maximum size and using adaptive rendering scale to stay within limits. To keep proportions right, you could use a dedicated displaying scale factor to accommodate for reduced rendering scales.
