### ISSUE TITLE
PdfTextPage.get_text() for rotated page incorrectly crops it

### ISSUE THREAD

**Issue by datacycling** [pypdfium2-team/pypdfium2#149]
If a page is rotated 90 degrees then `PdfTextPage.get_text()` should swap the width and height inside `get_text()`, currently it returns text only for a cropped area.

```python
Python 3.7.13 (default, Aug 12 2022, 05:20:12) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypdfium2 as pdfium
>>> pdfium.version.V_PYPDFIUM2, pdfium.version.V_LIBPDFIUM
('3.2.0', '5337')
>>> 
>>> pdf = pdfium.PdfDocument('R.P.STransfer05092013 175230.pdf')
>>> page0 = pdf.get_page(0)
>>> page0.get_width(), page0.get_height()
(1008.0, 612.0)
>>> page0.get_rotation()
90
>>> 
>>> text_page0 = pdf.get_page(0).get_textpage()
>>> all_str1 = text_page0.get_text()
>>> len(all_str1)
2971
>>> 
>>> pdfium.FPDFText_GetBoundedText(text_page0.raw, 0, 0, 1008, 612, None, 0)
2971
>>> pdfium.FPDFText_GetBoundedText(text_page0.raw, 0, 0, 612, 1008, None, 0)
4442
>>> 
```

Here is a link the [pdf file](https://www.police.rajasthan.gov.in/PoliceUser/UploadUtility/TransferFiles/R.P.STransfer05092013%20175230.pdf)

**Comment by mara004** [comment]
Ah, yes, absolutely. Thank you for reporting this.

However, what I'm wondering about is *where* we should swap width and height. Really in `get_text()` itself? Shouldn't rather `get_size()` return the rotated size in the first place?

Anyway, I think the required check will be
```python
if (rotation // 90) % 2 != 0:
    width, height = height, width
```

**Comment by mara004** [comment]
Whoops, `get_size()` already does return the rotated size, but GetBoundedText wants the non-rotated size.
So you're right the swapping needs to happen in `get_text()`.

**Comment by mara004** [comment]
I believe to have addressed the issue in the current development branch [`autoclose_via_weakref`](https://github.com/pypdfium2-team/pypdfium2/tree/autoclose_via_weakref). I think `FPDF_GetBoundedText()` indeed requires low-level PDF coordinates and not normalised positions.

Also, I added a second text extraction method `get_text_range()` that might be more suitable for just extracting all text on a page than the current boundary-based `get_text()`.

Now I get the following results:
```python
Python 3.10.5 (main, Jun 10 2022, 10:06:05) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypdfium2 as pdfium
>>> pdf = pdfium.PdfDocument("/home/mara/tmp/R.P.STransfer05092013 175230.pdf")
>>> page = pdf[0]
>>> textpage = page.get_textpage()
>>> all_str = textpage.get_text()
>>> len(all_str)
4442
>>> all_str_2 = textpage.get_text_range()
>>> len(all_str_2)
4526
>>>
```

**Comment by mara004** [comment]
Fix merged into main: https://github.com/pypdfium2-team/pypdfium2/commit/379b820c38bcf40fdc091f7c6e6b9113f434afdb

**Comment by datacycling** [comment]
Thanks a lot @mara004 will check this out.
