### ISSUE TITLE
pypdfium2 is temporarily broken on Docker (`page_allocator_internals_posix.h` error)

### ISSUE THREAD

**Issue by mara004** [pypdfium2-team/pypdfium2#154]
The documentation build for pypdfium2 3.6.0 failed on RTD:
https://readthedocs.org/projects/pypdfium2/builds/18490181/
```
Running Sphinx v5.3.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://pillow.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
myst v0.18.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=[], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [ 16%] changelog
reading sources... [ 33%] index
reading sources... [ 50%] planned_changes
reading sources... [ 66%] python_api
[FATAL:page_allocator_internals_posix.h(244)] Check failed: 0 == ret. : Operation not permitted (1)
Trace/breakpoint trap (core dumped)
```

However, it works for me locally with the same version of Sphinx.

Browsing PDFium's code, the source code form referenced in the error is located in `./base/allocator/partition_allocator/page_allocator_internals_posix.h`.

So it looks like PDFium is at fault?

**Comment by mara004** [comment]
Reported this to PDFium team: https://groups.google.com/g/pdfium/c/1VU4wZpYteA

**Comment by mara004** [comment]
Although this will probably be fixed in PDFium sooner or later, I think I'm going to look into hosting the docs on GitHub Pages as well. RTD uses a kind of strange setup and is not as configurable as a GitHub workflow.

**Comment by mara004** [comment]
I've experimented with GH Pages in a fork, and was basically able to use a preset workflow with minimal changes:
https://github.com/mara004/pypdfium2/blob/main/.github/workflows/gh_pages.yml
Amazingly quick & simple. The only problem is, I think we're not able to host multiple versions on GH pages, are we?

**Comment by tvasenin** [comment]
Same issue happens with pypdfium2 releases **3.6.0** and **3.7.0**, reproduced with Docker 20.10.21:

``` Dockerfile
FROM python:3.7.15-bullseye
RUN pip3 install pypdfium2==3.7.0
RUN python3 -c "import pypdfium2"
```

**Comment by mara004** [comment]
The RTD build works again, so I deduce that the issue is fixed.
