### ISSUE TITLE
Linux aarch64 builds require glibc >= 2.29 | pdfium(-binaries) issue

### ISSUE THREAD

**Issue by erdkse** [pypdfium2-team/pypdfium2#165]
Importing works well on AMD architecture but whenever I try to import on arm docker image I just can't load `pypdfium2`. I wonder if this is related to the aarch64 build or if there is something else?

Dockerfile base image is `python:3.10.9-slim-buster`, I can provide the same environment if needed

**Comment by mara004** [comment]
How did you install pypdfium2?
Are you sure you ended up with the right wheel? Could you try to explicitly install this one and see if it works? [pypdfium2-3.15.0-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl](https://github.com/pypdfium2-team/pypdfium2/releases/download/3.15.0/pypdfium2-3.15.0-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)
And could you check the output of `python3 -c "import platform; print(platform.machine())"`? It should be `aarch64`.

The binaries are just taken from the `pdfium-binaries` project, so not sure what could be wrong here...

**Comment by mara004** [comment]
BTW, if you know how to create a CI setup for architectures like aarch64, I'd be happy to hear about it or, even better, to take a PR integrating it into the build & test workflow. (Note that unfortunately I don't know Docker yet, so far never used it.)

**Comment by erdkse** [comment]
hey, the library fails to load on base image `python:3.10.9-slim-buster` but it is successful to load on `ubuntu:23.04`. Both of them are ARM, It works well with all AMD-based architectures that I tried.

I installed it by creating virtualenv in the docker image.

For sure, I would like to create a PR to test loading the library. It may take some time since I have other works to do. But it is on my mind, I will do it.

**Comment by mara004** [comment]
Aah, now I understand, that'll be since the binary requires a newer glibc than what buster provides, see https://github.com/bblanchon/pdfium-binaries/issues/82

**Comment by erdkse** [comment]
I actually installed that library with the latest version, but I am not sure what I did wrong, that is why I created the issue, thank you so much by the way. You are such a great open-source maintainer.

I will create both arm and amd test suites. Do you want me to create an issue for that so you can assign me.

**Comment by mara004** [comment]
Thanks, I just assigned you to this issue for simplicity if it's OK.

**Comment by mara004** [comment]
Good news, it looks like this issue will soon be fixed in pdfium: https://groups.google.com/a/chromium.org/g/chromium-dev/c/SdCs9k3celo/m/a6CtkDb2CQAJ

**Comment by erdkse** [comment]
wohoo perfect! Is there any communication channel that I can use to consider how to create ARM,AMD test suites with you? OR shall I use here?

**Comment by mara004** [comment]
You can either use this thread or send me an [email](mailto:geisserml@gmail.com).

The trouble is, I'm not really able to develop anymore since a few weeks (for personal reasons), and this might be a longer problem. You can still try to mail me but I can't guarantee for anything.

It's a pity because I'd like to finish the work started in the `devel` rsp. `devel-testsuite` branches, but it looks like I might have to take a longer break, or maybe even step down as maintainer entirely...
