### ISSUE TITLE
Provide a source build fallback

### ISSUE THREAD

**Issue by mara004** [pypdfium2-team/pypdfium2#19]
Add a generic source build strategy for platforms where we don't have pre-built binaries:
* Download DepotTools and PDFium
* Set configuration, optionally apply patches
* Perform the build
* Move header files and binary to `data/sourcebuild`
* Package a wheel

**Comment by mara004** [comment]
I've started experimenting in the [`sourcebuild`](https://github.com/pypdfium2-team/pypdfium2/tree/sourcebuild) branch

**Comment by adam-huganir** [comment]
I look forward to seeing out it works, the ctypesgen builds are always temperamental for me for any project I use them for

**Comment by mara004** [comment]
Yeah, I concur. Being dependent on external binaries is a big limitation, that's why I started working on this...

**Comment by mara004** [comment]
@adam-huganir I've pushed a commit incorporating more patches. The generated binary now works and our tests pass.

**Comment by mara004** [comment]
@adam-huganir I believe that the source build script should be pretty solid now. In case you haven't done yet, could you maybe try it on your device, to confirm that PDFium builds correctly just by running the script, and to make sure I haven't missed any external dependencies?

**Comment by adam-huganir** [comment]
Ok, so fresh clone of main, in a fresh python 3.8.12 environment:

1. Source build works with no issues, though I have a bunch of dev dependencies in general on my computer, so this should probably be tested in a vm at some poitn
2. because sourcebuild generates `libpdfium.so` library instead of one named `pdfium` I had to change the load line in  `pypdfium2/_pypdfium.py`

```
   806 # Begin libraries
>> 807 _libs["pdfium"] = load_library("libpdfium.so") # from 'pdfium'
```
so you will need to change wherever that is generated (I guess cytpesgen call time?)

After changing that and installing Pillow everything worked as expected :+1:

**Comment by mara004** [comment]
Thanks for testing!

> because sourcebuild generates `libpdfium.so` library instead of one named `pdfium` I had to change the load line in `pypdfium2/_pypdfium.py`

I already thought about that when writing the script, and had implemented the option `--destname` to allow for renaming the binary, e. g. to `pdfium`. However, on my machine it was also possible to load `libpdfium.so`, but that might be because I'm using a newer version of ctypesgen that I installed from the current ctypesgen git repository.

**Comment by mara004** [comment]
> After changing that and installing Pillow

Oh, that's a good catch - I totally forgot to list Pillow as installation requirement in `setup.cfg`! I'll fix that soon.

**Comment by mara004** [comment]
> so this should probably be tested in a vm at some point

I'm currently setting up an OpenSUSE Leap 15.3 VM ...

**Comment by mara004** [comment]
> Source build works with no issues, though I have a bunch of dev dependencies in general on my computer, so this should probably be tested in a vm at some point

I just successfully built PyPDFium2 in VirtualBox with OpenSUSE Leap 15.3.

**Comment by mara004** [comment]
> Source build works with no issues, though I have a bunch of dev dependencies in general on my computer, so this should probably be tested in a vm at some point

I just successfully built PyPDFium2 in VirtualBox with OpenSUSE Leap 15.3. However, I yet found some important external dependencies that I've listed in `DEPS.txt` now.
