### ISSUE TITLE
PDF to Image conversion skips signature image created with Adobe Reader

### ISSUE THREAD

**Issue by Tlaloc-Es** [pypdfium2-team/pypdfium2#191]
Hello,

I'm trying to convert a PDF document into an image using the render method in version 4.2.0 of the library. However, the signature image created with Adobe Reader is not being rendered in the resulting image.

Here's the code snippet I'm using:

```python
pdf_bitmap = page.render(
    scale=3,
    rotation=0,
    crop=(0,0,0,0),
    grayscale=False,
    optimize_mode=None,
    draw_annots=True
)
```

Is there a way to include the signature image in the resulting image? Any help or suggestion would be greatly appreciated. Thank you.

**Comment by mara004** [comment]
Maybe the image is part of an AcroForm or something? Try calling `pdf.init_forms()` directly after constructing the `PdfDocument`. If that does not fix the problem, I'd need to see the particular PDF.

**Comment by Tlaloc-Es** [comment]
Here's the corrected text with minor edits and fixed typos:

We tried the following code:

```python
pdf = pdfium.PdfDocument(source)
pdf.init_form()
page = pdf.get_page(0)
pdf_bitmap = page.render(
    scale=3,
    rotation=0,
    crop=(0,0,0,0),
    grayscale=False,
    optimize_mode=None,
    draw_annots=True
)
pdf_bitmap.to_pil().save(target)
```

However, it did not work and it's possible that the PDF is an AcroForm. How can I check this? Unfortunately, I cannot share the document as it's confidential. PDF2Miner works but it's too slow. I am not sure if this will help identify why the signature is not appearing

**Comment by mara004** [comment]
If the above does not work, then it's probably not about forms, but you could run
`print( pdfium.internal.FormTypeToStr.get( pdf.get_formtype() ) )` to confirm.

If you can't share a PDF that demonstrates the problem, then I'm afraid we can't help you.

Apart from that, what's PDF2Miner? Is this another PDF rendering engine? Could you share a link?

**Comment by Tlaloc-Es** [comment]
Hi, sorry the library is PDF2IMG was a typo, the function returns None.

**Comment by mara004** [comment]
Hmm, could you maybe provide/craft a non-confidential PDF that shows the problem (or whoever has such a document or is capable of creating one) ?
Otherwise, I'll have to close this issue. Also, this sounds like a problem with PDFium itself, not with the Python bindings.

**Comment by Tlaloc-Es** [comment]
I apologize, but I was unable to create the PDF file as it was created in an office and I am not familiar with the process. However, I found that another library which also uses pdfium had faced a similar issue during implementation. You may find this information useful, and I recommend taking a look at this link: https://github.com/pvginkel/PdfiumViewer/issues/87.

**Comment by mara004** [comment]
Thanks, the [linked test file (archive url)](https://web.archive.org/web/20150529021955/https://blogs.adobe.com/security/SampleSignedPDFDocument.pdf) shows the problem. That's exactly what I was looking for. I'll investigate.

**Comment by mara004** [comment]
I found and somewhat fixed an issue with the multi-page renderer not initializing the formenv in worker processes (see 260140b). The file mentioned in https://github.com/pypdfium2-team/pypdfium2/issues/191#issuecomment-1468730115 (which has AcroForms) now renders correctly with the multi-page renderer (as used by the `pypdfium2 render` CLI).
But this does not look like your issue, because you're using the single-page renderer, and your document has no forms according to https://github.com/pypdfium2-team/pypdfium2/issues/191#issuecomment-1468533502.

**Comment by mara004** [comment]
`pypdfium2 render SampleSignedPDFDocument.pdf -o out/` prints
`Unsupported PDF feature: Signature annotation` for me.

So even if it seems to work for this particular document, it might be a feature not fully supported by PDFium.
Can you check if PDFium in Chrome/Chromium renders your signature PDF correctly? If not, you'd need to it report upstream.

**Comment by Tlaloc-Es** [comment]
Thank you, mara004. You work very quickly. Unfortunately, I was unable to check the information you provided due to the high security environment in which the PDFs are stored. Therefore, I suggest we close this issue for now. If I am able to access the information in the future, I will be sure to share it with you.

**Comment by mara004** [comment]
Thanks, feel free to reopen if you get access to the PDF again.
And thanks for making me aware of the forms issue with the document-level renderer, although it was somewhat unrelated.
