### ISSUE TITLE
Pange.render grayscale is inversing the colors

### ISSUE THREAD

**Issue by naourass** [pypdfium2-team/pypdfium2#199]
I'm using PyPdfium 4.4.0.

My PDF page is black text on white background. When I call render with grayscale off, it's rendered correctly. But when I set grayscale to True, the colors of the rendered image are inversed (white text on black background).

Is that normal behaviour?

**Comment by mara004** [comment]
> The problem was with matplotlib imshow mapping the wrong colors. The image is actually rendered properly.

Thanks for clarifying!
