### ISSUE TITLE
No dependencies on installation

### ISSUE THREAD

**Issue by vletard** [pypdfium2-team/pypdfium2#200]
Installing pypdfium2 from pip does not install the dependencies. I had to analyze the code to find why I got this message:
```
AttributeError: 'NoneType' object has no attribute 'Image'
```

Dependency installation should be added in `setup.py` to avoid this.
Meanwhile, a clear error message in [bitmap.py](https://github.com/pypdfium2-team/pypdfium2/blob/main/src/pypdfium2/_helpers/bitmap.py) would at least help identifying the problem.

**Comment by mara004** [comment]
PIL is optional, so not installed by default. We manage optional deps with requirements files, see the `req/` directory.
Downstream projects using any of the PIL dependent methods (`to_pil()`, `from_pil()`) should specify it as mandatory dependency.

A better error message may be a thing to consider, though.

**Comment by mara004** [comment]
> A better error message may be a thing to consider, though.

Turns out to be somewhat inconvenient, unfortunately, as PIL is used in various places/fashions across the support model. For now, I think it's sufficient if the docs state where PIL is needed.
