### ISSUE TITLE
Extracting text blocks

### ISSUE THREAD

**Issue by guyrosin** [pypdfium2-team/pypdfium2#210]
Hi,
It seems text extraction behaves very differently when using `get_rect()` and `get_text_range()`.
For example, in [this PDF](https://drive.google.com/file/d/1XnIQmY7ilrrrO_uuMDF5T6BfaZ5573QM/view?usp=sharing), `get_text_range()` works as expected, but sequentially calling `get_rect()` results in corrupted text.

Here's my code:
```python
for i in range(text_page.count_rects()):
    rect = text_page.get_rect(i)
    text = text_page.get_text_bounded(*rect)
    print(text)
```
Here's the start of the output. Note parts of the text are corrupted.
```
ACCEPTED MANUSCRIPT
rdia, Steven Tuyishimea, Hiromi Muramatsua, Katalin K
ing K Tamb, Thomas D Maddenb, Michael J Ho
a
nt of Medicine, University of Pennsylvania, Philadelphia
herapeutics, Vancouver, British Columbia, Canada, V6T 
ding author:
ww@mail.med.upenn.edu
5 573 8491
349 5111
ecent years, in vitro transcribed messenger RNA (mRN
ntial therapeutic platform. To fulfill its promise, effec
 specific cell types and tissues needs to be a
es (LNPs) are efficient carriers for short-interfering R
nical trials. However, little is known about the poten
NA. Here, we generated mRNA-LNPs by incorporating 
eudouridine-containing mRNA comprising codon-o
nto stable LNPs. Mice were injected with 0.005-0.250 
Ps by 6 different routes and high levels of protein tran
using in vivo imaging. Subcutaneous, intramuscular 
 the LNP-encapsulated mRNA translated locally at the 
0 days. For several days, high levels of protein prod
n the lung from the intratracheal administration of mRN
ACCEPTED MANUSCRIPT
Expression kinetics of 
...
-
encoding mRNA into rats with diabetes insipidus
1
```

Here's a screenshot of most of the PDF for convenience: 
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1250162/233403730-3b2e66db-0c5b-4c24-9c05-7d9933b03efe.png">

[My ultimate goal is to extract text blocks, which are more abstract and natural than text rectangles. For example a text line can be composed of multiple rectangles, and I'm trying to merge close rectangles into blocks. This functionality is included for example in [pymupdf](https://pymupdf.readthedocs.io/en/latest/textpage.html#TextPage.extractBLOCKS)]).

**Comment by mara004** [comment]
pypdfium2 transparently wraps pdfium's APIs - you'll have to ask about that upstream.
To my understanding, this isn't a bug, but rather the way how pdfium's current APIs are designed.
AFAIK, pdfium itself does not provide an API to group/detect larger text blocks yet, but you may browse pdfium's headers to check yourself.

However, as PDF only encodes the positions of single characters, text block grouping always depends on heuristics.
You could try implementing your own text grouping just with pdfium's char API, but that'll be complicated :)

The examples in [pypdfium-explore](https://github.com/pmbaumgartner/pypdfium-explore) by @pmbaumgartner seem  related, at least tangentially - maybe they might interest you? (Sadly they're a bit outdated, still using the old v3 API.)

**Comment by guyrosin** [comment]
Got it, thanks!

**Comment by mara004** [comment]
Linking https://crbug.com/pdfium/2025 reported by @guyrosin
