### ISSUE TITLE
How to extract character with coordinates from PDF using pypdfium2 ?

### ISSUE THREAD

**Issue by pranayamhatre175** [pypdfium2-team/pypdfium2#214]
Hi,

I am trying to extract character and its coordinates using following way: 

1. I am providing index by iterating textpage.count_chars().
2. to get coordinates I am using textpage.get_charbox(index)
3. to get character I am using textpage.get_text_range(index, count =1)

For some PDFs I am getting wrong coordinates for character using above method.  Is I am using correct way to extract character and coordinates ? If yes then why I am getting wrong coordinates for characters in some PDFs ?

If I am using wrong way to extract character and coordinates then please provide right method for the same ?

**Comment by mara004** [comment]
That sounds like correct usage. Concerning 3, if you only want to extract single chars, you can also use [`FPDFText_GetUnicode()`](https://pdfium.googlesource.com/pdfium/+/832a694e52c44e206598eff8c7d1797d47117d1b/public/fpdf_text.h#62) from `pypdfium2.raw` (raw pdfium API).

Can you share a minimal reproducible exapmle where you believe `get_charbox()` returns wrong coordinates?

In general, `get_charbox()` returns values for (left, bottom, right, top) *in PDF canvas units*.
Note that, when translating PDF coordinates to bitmap coordinates (and vice versa), you're not just done with translating origin (bottom left <-> top left), but a lot more needs to be taken into account. (Read what the PDF spec says on the coordinate system.) I recommend using `FPDF_PageToDevice()` / `FPDF_DeviceToPage()` for that operation (also raw API, defined in `fpdfview.h`).

**Comment by mara004** [comment]
Hmm, I browsed pdfium's bug tracker a bit, and by chance found the following two bug reports that seem related:
https://bugs.chromium.org/p/pdfium/issues/detail?id=1821
https://bugs.chromium.org/p/pdfium/issues/detail?id=1562

So possibly this is an actual pdfium bug you may be experiencing here. However, as mentioned above, a test file + reproducing code would be important.

**Comment by mara004** [comment]
If there's no response, I'll close this issue eventually since it doesn't seem to be caused by pypdfium2 itself.

**Comment by pranayamhatre175** [comment]
Hi,
Sorry for late reply I have tested PDFs in which I have found above issue with your given solution i.e FPDFText_GetUnicode(). Problem resolved for those PDF but still I am testing this solution.

Is there any way to get words , sentences and there coordinates using pypdfium2 ? I have tried certain way but not able to get for all PDFs for some its working for some its not.

One more issue I am facing I have PDF with 0 orientation. but I am getting coordinates rotated by counterclockwise 90 degree using get_charbox(). Do you know what will be the issue ? Using pypdfium2 I have checked rotation its saying 90 degree.

**Comment by mara004** [comment]
TBH, I'm a bit confused by what you're writing.

> Sorry for late reply I have tested PDFs in which I have found above issue with your given solution i.e FPDFText_GetUnicode(). Problem resolved for those PDF but still I am testing this solution.

That's strange, `textpage.get_text_range(index, count=1)` should yield the same result as `FPDFText_GetUnicode()`, I thought this merely as a stylistic improvement.

> Is there any way to get words , sentences and there coordinates using pypdfium2 ? I have tried certain way but not able to get for all PDFs for some its working for some its not.

Well, there's the rectangle API (`count_rects()`, `get_rect()`) but (to my understanding) it may return anything between a few chars and a whole sentence, so it only groups chars by proximity without a particular target.
Unfortunately, pdfium does not provide specific APIs to distinguish words/sentences yet, but we recently got another report related to this topic (#210) which resulted in a lengthy feature request upstream (https://crbug.com/pdfium/2025)

> One more issue I am facing I have PDF with 0 orientation. but I am getting coordinates rotated by counterclockwise 90 degree using get_charbox(). Do you know what will be the issue ? Using pypdfium2 I have checked rotation its saying 90 degree.

Not sure if I'm interpreting this correctly, but I think the following: In PDF, rotation modifies the coordinate system, so coordinates are always relative to the non-rotated page. If you have a page defining rotation 90° and intend to get visual coordinates, you need to apply that rotation to the char box, e. g. by translating the values with [`FPDF_PageToDevice()`](https://pdfium.googlesource.com/pdfium/+/5b81b29a8f001b4a076418b063012a56ba253f0c/public/fpdfview.h#997).
That's what I already hinted at above.

(Note that rotation is only a structural value that does not tell how the content is actually oriented, i. e. you can get a page with rotation 90° but visually the page may look upright.)

**Comment by mara004** [comment]
Since there has been no response for 2 weeks, I'm closing this for now.
@pranayamhatre175 You're free to reopen/continue this thread if you feel like it.
