### ISSUE TITLE
Pypdfium duplicates running app when called from pyinstaller exe

### ISSUE THREAD

**Issue by ramsluk** [pypdfium2-team/pypdfium2#227]
I am using pypdfium2 to convert a pdf file  with one page to a png file like so: 

```
tmp_pdf = pdfium.PdfDocument("tmp_png.pdf")
renderer = tmp_pdf.render(
   pdfium.PdfBitmap.to_pil, page_indices=0, scale=300/72
)
for image in renderer:
   image.save("tmp.png")
```

Everything works out when called from a normal python script. After converting my project to an .exe with pyinstaller it does not work anymore. My user interface is somehow duplicated and everything freezes. When closing the new duplicated window I get the following error message: 

```
File "pypdfium2\_helpers\document.py", line 635, in render
    yield from pool.map(invoke_renderer, page_indices)
File "concurrent\futures\process.py", line 562, in _chain_from_iterable_of_lists
File "concurrent\futures\_base.py", line 609, in result_iterator
File "concurrent\futures\_base.py", line 446, in result
File "concurrent\futures\_base.py", line 391, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

I am using this version: `pypdfium2 4.9.0 (libpdfium 5744, pdfium-binaries default build)` with `Python 3.9.13` and `Pyinstaller 5.10.1`

I tried to explicitly close the `tmp_pdf` which  did not change anything in the outcome.

**Comment by mara004** [comment]
> I am using this version: pypdfium2 4.9.0 (libpdfium 5744, pdfium-binaries default build) with Python 3.9.13 and Pyinstaller 5.10.1

PS: Although not related to this particular issue, I recommend that you update to the latest version 4.15

**Comment by ramsluk** [comment]
Okay sorry for the inconvenience and thank you very much for your reply and tip! @mara004

**Comment by mara004** [comment]
No problem. I hope this actually works, seeing as I haven't used pyinstaller yet.
