### ISSUE TITLE
not found some pdfium api

### ISSUE THREAD

**Issue by cole-dda** [pypdfium2-team/pypdfium2#236]
import pypdfium2.raw as pdfium_c

why not found: 
pdfium_c.FPDFOBJ_GetObjNum(...)

**Comment by mara004** [comment]
Running `grep -r FPDFOBJ_GetObjNum` in `pdfium/public` returns nothing.
I'm not aware of any recent API-breaking changes in pdfium, either.
You simply cannot access functions that do not exist in pdfium.

**Comment by mara004** [comment]
I conducted a brief web search: apparently [`FPDFOBJ_GetObjNum()`](https://pdfium.patagames.com/help/html/M_Patagames_Pdf_Pdfium_FPDFOBJ_GetObjNum.htm) is part of the commercial Patagames C# SDK, which seems to be a superset of the open-source pdfium.

Sadly it's closed-source, but the [functions list](https://pdfium.patagames.com/help/html/Methods_T_Patagames_Pdf_Pdfium.htm) is interesting enough.
Apparently they have added the raw access API that I'm missing so much in pdfium (pdf dictionaries, arrays, streams, etc.) They also seem to have exposed the matrix API, added support for OCGs (layers), and much more ...

If anyone has purchased a binary + headers for this SDK, provided that all these new functions are C ABI accessible and the SDK is really a mere superset of google's pdfium, it may be possible to use with pypdfium2.

**Comment by mara004** [comment]
FYI, I posted this information on https://crbug.com/pdfium/1694#c5
