### ISSUE TITLE
[Docs] About the variable n_digits

### ISSUE THREAD

**Issue by SWHL** [pypdfium2-team/pypdfium2#255]
Thanks for your great work.

When I look up the [Usage of README](https://github.com/pypdfium2-team/pypdfium2/blob/main/README.md#usage), I can't find the place where the `n_digits` is been declared.

I hope the author can clarify this place, reduce other people's confusion, and make this repository better.

**Comment by mara004** [comment]
Thanks for letting me know.
I guess this was a copy-paste error when taking over excepts of code, this is always prone to undeclared variables.
