### ISSUE TITLE
Endless loop parsing certain files

### ISSUE THREAD

**Issue by b-maldoca** [pypdfium2-team/pypdfium2#257]
i am running into an endless loop when parsing 3013b1d298ce7af8e5965a1dbba820c3ca99c7c042eaae926408dd75769fe155,
d1f629b873ad4db1fa6895f6b160b3f3ea96d8048782d709fdacce8f4bf1c3b5 or 1f04384517967a26cc0ffe1958c935f4c9f1f6a55e03391c05dbde0c28a4da45

Given I can open them in Chrome (i.e. pdfium) I assume the problem is within pypdfium

**Comment by mara004** [comment]
Please actually attach the files, otherwise it's impossible for us to investigate.
Also please detail what parsing exactly you are doing, i.e. post a code snippet or state the problematic functions.
Further, we need to know which version of pypdfium2 you are using.

**Comment by mara004** [comment]
@b-maldoca I conducted a quick github web search of https://github.com/google/maldoca, where presumably the files are supposed to come from (given you account name & activity), but was unable to find them.

**Comment by b-maldoca** [comment]
just for ref, the files are available on https://www.virustotal.com/gui/home/search

turns out the problem was in apache beam, not pypdfium. sorry, for the inconvenience!

**Comment by mara004** [comment]
OK, no problem. Thanks for reporting back.
However, virustotal doesn't actually offer to download the files, does it?
But I suppose a `Details -> Names -> Web search -> Download -> Hash check` approach should probably yield.

**Comment by mara004** [comment]
I was able to locate [3013b1d](http://www.mg-dianzi.com/Uploads/20200323021057_972531.pdf) and [d1f629b](https://mg-dianzi.com/Uploads/20200528101435_386649.pdf) (both rendering fine with pypdfium2), but could not yet get hands on `1f04384` (`w_doc03b1.pdf`).

**Comment by b-maldoca** [comment]
aghhh, seems one needs a virustotal account to download them...

yeah, i managed to parse all 3 files with pypdfium2 when doing so without apache beam, i.e. beam is the problem not pypdfium2.

**Comment by mara004** [comment]
Just out of interest, I'd still like to see the file. Could you possibly attach it here or something?

**Comment by b-maldoca** [comment]
[1f04384517967a26cc0ffe1958c935f4c9f1f6a55e03391c05dbde0c28a4da45.zip](https://github.com/pypdfium2-team/pypdfium2/files/12621628/1f04384517967a26cc0ffe1958c935f4c9f1f6a55e03391c05dbde0c28a4da45.zip)

**Comment by mara004** [comment]
Thanks!
