### ISSUE TITLE
PyPI: enable account 2FA and switch to "trusted publishing" (OIDC)

### ISSUE THREAD

**Issue by mara004** [pypdfium2-team/pypdfium2#258]
Reminder that we need to address (Test)PyPI 2FA requirements until the end of year to prevent being locked out.

Also, we want to switch to OIDC based trusted publishing, which allows us to get rid of the permanent token.
See https://docs.pypi.org/trusted-publishers/adding-a-publisher/ and https://docs.pypi.org/trusted-publishers/using-a-publisher/

**Comment by mara004** [comment]
OK, part 1 done, I've set up 2FA for my account.

@adam-huganir @YinlinHu @mkroutikov According to an e-mail notification from PyPI, which you should have received, too, 2FA would become mandatory by the end of this year. (They don't say what happens if you don't, though.)
As of this writing, acccording to the Collaborators page, none of you currently have 2FA enabled. This is something you might want to change. (Sorry if this annoys you. Disclaimer: It was not me who made the decision.)

![image](https://github.com/pypdfium2-team/pypdfium2/assets/65915611/24b8478b-4c26-4e5a-985a-ad41a3c9f479)

**Comment by mara004** [comment]
@adam-huganir @YinlinHu @mkroutikov Yet another thing, I'd also like to add you as collaborators for TestPyPI, but none of you seem to have a (working) TestPyPI account of same name.

@mkroutikov For you, an account seems to exist, but TestPyPI doesn't accept an invitation attempt, saying `[Error] User 'mkroutikov' does not have a verified primary email address and cannot be added as a Maintainer for project`

**Comment by mara004** [comment]
Note to self: Configured trusted publishers for PyPI and TestPyPI, but they are not actually used yet; upload is currently still done with twine via API token.
The "pending project name" for TestPyPI is `pypdfium2-testing-donotuse`.

**Comment by adam-huganir** [comment]
done :+1:

**Comment by mara004** [comment]
@adam-huganir Thank you, that was quick! I just sent you the TestPyPI invitation.

**Comment by mara004** [comment]
Note to self: PR #259 merged, `release` environment configured (currently allows main branch only), API tokens removed from PyPI, TestPyPI and GH. Let's hope for the best.

**Comment by mara004** [comment]
Note to self: Release workflow currently failing due to recent changes.
However, not at PyPI, but before that: on the repo push step (permission denied). Not quite sure why; might have something to do with the new permissions section.
I had also removed an `AUTORELEASE_TOKEN` which I think was unused, but this should probably not be the cause.

**Comment by mara004** [comment]
OK, push fixed with 84e4d9deaeb9c268017ebc218b196c158ff776c3, but new issue with TestPyPI now.

**Comment by mara004** [comment]
OK, finally working. Something was wrong with the TestPyPI config, just had to add the trusted publisher again to `pypdfium2` project.
Not sure why we needed the odd `pypdfium2-testing-donotuse` deputy project in the first place. (I'm wondering if we can delete it now?)

Only GH pages rebuild failed due to interruption, but this was probably not a bug.

**Comment by mara004** [comment]
> Not sure why we needed the odd pypdfium2-testing-donotuse deputy project in the first place.

Ah, I was just on the wrong page yesterday (https://test.pypi.org/manage/account/publishing/, which is for new projects only), but we actually needed https://test.pypi.org/manage/project/pypdfium2/settings/publishing/ for the existing project. Guess I was too tired...

> (I'm wondering if we can delete it now?)

Yes, done.
