### ISSUE TITLE
Compile error under nvidia jetson arm64 environment

### ISSUE THREAD

**Issue by hzrlsd** [pypdfium2-team/pypdfium2#264]
hardware:nvidia jetson xavier ARM64
software:ubuntu 20.04 python 3.8.10 gcc 9.4.0
compile pypdfium2-4.20.0.tar.gz
error info：
<img width="438" alt="image" src="https://github.com/pypdfium2-team/pypdfium2/assets/140566703/42f064e1-bc21-42e5-9e9d-230b121ea6fa">
<img width="431" alt="image" src="https://github.com/pypdfium2-team/pypdfium2/assets/140566703/746a831a-f0d4-402b-a45a-ca9e5fc3ce41">
So how to solve this problem？Thanks

**Comment by hzrlsd** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法亲自回复您的邮件。我会尽快给您回复。

**Comment by mara004** [comment]
New release published: https://github.com/pypdfium2-team/pypdfium2/releases/tag/4.21.0

**Comment by mara004** [comment]
I believe https://github.com/pypdfium2-team/pypdfium2/issues/264#issuecomment-1757695862 should address this issue, so I'll close this for now. Feel free to comment/reopen if there are any questions left.

**Comment by hzrlsd** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法亲自回复您的邮件。我会尽快给您回复。
