### ISSUE TITLE
Platform support and testing status

### ISSUE THREAD

**Issue by mara004** [pypdfium2-team/pypdfium2#3]
Platforms we build wheels for and their current testing status:

* macOS x64:
  Tested, works (10.11.6 El Capitan  / 10.15.7 Catalina / 11.6.1 Big Sur)
* macOS arm64/M1:
  Tested, works (11.6 Big Sur)
* Linux x64 glibc:
  Tested, works (Ubuntu 20.04, Python 3.8)
* Linux x86/i686 glibc:
  Untested
* Linux aarch64/arm64 glibc:
  Tested, works (via emulation in GitHub workflow)
* Linux armv7l/armhf glibc:
  Tested, works (Debian 9, Raspberry Pi 2, Python 3.9)
* Linux x64 musl:
  Untested
* Linux x84/i686 musl:
  Untested
* Windows x64:
  Tested, works (Windows 8.1)
* Windows arm64:
  Untested
* Windows x86 (i. e. 32-bit):
  Untested

Summary: At the moment, 6 of 11 wheels are confirmed to work.
pypdfium2 does not only run with [CPython](https://github.com/python/cpython), but also with [PyPy](https://www.pypy.org/).

**Comment by mlove4u** [comment]
macOS x86_64
**・10.11.6
・10.15.7**
 are confirmed to work.
![10 11 6](https://user-images.githubusercontent.com/18019314/148499262-6671d68c-d9a2-49e7-ba9f-b0cd824bb46f.png)
<img width="713" alt="10 15 7" src="https://user-images.githubusercontent.com/18019314/148499367-ffd87623-4df4-4cb0-9fd9-87caae97d510.png">

**Comment by mara004** [comment]
Thanks, I've updated the status above!

**Comment by mlove4u** [comment]
OS: macOS Big Sur(11.6)
CPU: **Apple M1**

**1. Python3.8.9(default pre-installed in Big Sur).** Processing stopped in "Preparing metadata (setup.py)..."
![3 8 9](https://user-images.githubusercontent.com/18019314/148908785-f750ff9f-1f12-4b5e-9609-4cb7e3354494.png)

**2. Python3.10.1(Downloaded from python.org).** Only pypdfium2-0.1.0 can be installed. 
`pip3 install -U pypdfium2`
![3 10 1](https://user-images.githubusercontent.com/18019314/148908903-3ec5e721-3c95-4311-9273-f91e046b39a1.png)
.

**Comment by mara004** [comment]
Many thanks for testing again, this is really apprectiated.

The Apple M1 result is explainable. We currently don't have pre-built binaries for this platform, so it downloads the source distribution and tries to compile PDFium, which will likely fail because the build system of PDFium is profoundly complex, and it seems that it's mainly designed for cross-compilation. However, you could run the separate build script `build_pdfium.py` and see what errors it reports. I will also open a ticket at pdfium-binaries and ask whether they could build for M1, but I don't know if it's feasible.

The other issue appears to be a problem with wheel naming that I will have to investigate more detailed. Meanwhile, could you try to download [this file](https://files.pythonhosted.org/packages/83/ad/59a814136cf5dbc85138bd2be77d7a6ec0f3dee001635ced039427abab6f/pypdfium2-0.8.0-py3-none-macosx_10_11_arm64.whl) and install it manually using `pip3 install pypdfium2-0.8.0-py3-none-macosx_10_11_arm64.whl` and see if that works?

**Comment by mara004** [comment]
I pushed a commit that should (hopefully) fix the issue with wheel naming. I'll upload a new minor release that you can try.

**Comment by mara004** [comment]
Many thanks for testing again, this is really apprectiated.

As far as I can see, this was an issue with wheel naming. I have pushed a commit that should fix it, and uploaded a new minor release that you can try: https://pypi.org/project/pypdfium2/0.8.1/

**Comment by mlove4u** [comment]
Thanks for the fix.
V0.8.1 was successfully installed on **macOS Big Sur(11.6) with Apple M1 chip**.
And, all passed!
![arm64](https://user-images.githubusercontent.com/18019314/149042939-73f73f01-202e-40b1-83d9-9ce0cfb7338b.png)

**Comment by mara004** [comment]
Super, thanks!

**Comment by mara004** [comment]
Hi @mlove4u,
I recently made some changes to macOS wheel tags, which I believe will enable compatibility with more versions of macOS.
Just to make sure my changes did not break anything, could you please test again? You'll want to use the following command to install the beta version containing the changes:
```
python3 -m pip install -i https://test.pypi.org/simple/ pypdfium2==0.13.2
```
Testing macOS x86_64 would be sufficient to me (if this works, then the other one should probably do as well). However, if you also have access to ARM it would be really nice if you could try both.
Thanks in advance.

**Comment by mlove4u** [comment]
@mara004 
There is no problem in macOS Big Sur(11.6.1) with Intel CPU. And I will test it in ARM later today.

![intel](https://user-images.githubusercontent.com/18019314/154874514-7515f27e-3d46-459d-8f1e-3862a0b31af1.png)

**Comment by mlove4u** [comment]
ARM(macOS Big Sur(11.6)) test also passed!

**Comment by mara004** [comment]
Thanks for the quick response!

**Comment by mara004** [comment]
@mlove4u Not sure if you are still interested in pypdfium2, but might I ask for your testing help with M1 once more?
I would like to find out whether `pdf.save()` works on M1, because it involves a callback that presumably needs to both execute and write permission, which M1 forbids.

Installing latest pypdfium2, running the test suite and sending me the output to check if this works or not would be really helpful.
I believe the saver test cases were only added shortly after https://github.com/pypdfium2-team/pypdfium2/issues/3#issuecomment-1010509777 (Jan 12) vs. https://github.com/pypdfium2-team/pypdfium2/commit/c76e892ab41ec91ff73bb19c91ce2d156fef759c (Jan 22).
Unfortunately, on the second case in February, you might not have run the test suite as I said it would be OK to only see if the wheel installed...

**Comment by mlove4u** [comment]
@mara004 You are welcome. These are my environments , I run the test files and all passed!

1. Intel CPU, macOS Big Sur(11.7.10): passed
2. M1 macOS Ventura 13.2.1: passed
3. M2 macOS Sonoma14.1.1: passed

**Comment by mara004** [comment]
Thanks for the quick response! Glad it passed.
jbarlow83 also mentioned that ctypes implements callbacks differently, so the problem seems to be limited to cffi.
