### ISSUE TITLE
Weird "PDFium: Data format error" when using pypdfium2 in Celery task.

### ISSUE THREAD

**Issue by elonzh** [pypdfium2-team/pypdfium2#309]
### Checklist

- [X] I confirm to be using an **official package** of `pypdfium2` from `PyPI` or `GitHub/pypdfium2-team`.
- [X] I have read and acknowledged the [response policy](https://github.com/pypdfium2-team/pypdfium2#contributions).

### Description

I am using pypdfium2 reading PDF metadata and texts with celery workers.

Celery workers runs in thread pool mode with 4  concurrencies. 

Those tasks will start failing randomly as the sametime even files are valid PDF, and it seems can't recover unless I restart the container.

Seems it's a threading issue because [PDFium is not thread-safe](https://pypdfium2.readthedocs.io/en/stable/python_api.html#thread-incompatibility)?

At first, I suspected whether it was a system load problem(CPU/Memory),  but I think it is not related with system load after two or three days of observation.

![image](https://github.com/pypdfium2-team/pypdfium2/assets/8749411/308b964d-ed6e-4014-a9b5-73bf5997b94d)

![image](https://github.com/pypdfium2-team/pypdfium2/assets/8749411/cfa7e83d-7c74-4ca1-9503-a551c6c5b10b)

### Install Info

```shell
pypdfium2 4.27.0
pdfium 123.0.6281.0
Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
```

### Validity

- [X] I confirm that I ran all commands, and pasted the whole output.

**Comment by mara004** [comment]
Yes, it is not allowed to access pdfium functions simultaneously across different threads. If that is not ensured, then arbitrary issues may arise (including security issues).
If you are sure the input data is correct (e.g. by testing with a single-threaded script), then this will likely be the cause.

**Comment by mara004** [comment]
However, if it's 4 concurrent tasks in a thread pool, then I'd expect that it should crash somewhat immediately.
Your report suggests to me it might seem to work longer than that?

**Comment by elonzh** [comment]
Yes, those tasks continuously complains "PDFium: Data format error" and the worker doesn't exit.

**Comment by edWin-m** [comment]
@elonzh How were you able to resolve this issue?

**Comment by elonzh** [comment]
> @elonzh How were you able to resolve this issue?

Just change worker pool type to prefork type.

**Comment by homeant** [comment]
How to solve this problem in fastapi, does any expert know?

**Comment by elonzh** [comment]
@homeant lock resource between operations should be ok.

**Comment by HaoRenkk123** [comment]
> fastapi中如何解决这个问题，有高手知道吗？
Excuse me, has it been resolved? I am also using FastAPI+ThreadPoolExecutor, and in each sentence of pdfium PdfDocument() has added a global lock:
with pdf_lock:
pdf_doc = pdfium.PdfDocument(pdf_path)
But it still reports that kind of mistake

**Comment by mara004** [comment]
@HaoRenkk123 This is not a pypdfium2 issue, but a caller-side integration issue.
I don't use celery/fastapi personally. Take a look at the hints provided by @elonzh.
Note that only locking `PdfDocument` construction is not sufficient: you'd have to guard all code that uses pdfium. It's not just `PdfDocument`, no (py)pdfium APIs at all may be called simultaneously from different threads.

**Comment by edWin-m** [comment]
> > @elonzh How were you able to resolve this issue?
> 
> Just change worker pool type to prefork type.

@HaoRenkk123 You can start from here.  That worked well with my implementation.  I am using it with FastAPI.
