### ISSUE TITLE
Feedback wanted: incoming changes in pdfium-binaries

### ISSUE THREAD

**Issue by bblanchon** [pypdfium2-team/pypdfium2#47]
Hi,

I'm the creator of [pdfium-binaries](https://github.com/bblanchon/pdfium-binaries), which host pre-build binaries of PDFium that this project uses.

You probably noticed that the Windows packages are slightly different from the other packages because the import library is not in `lib/`, but in `lib/x86/`, `lib/x64/` or `lib/arm64/`. Similarly, the DLL is not in the `bin/` but in a subfolder.
I'm currently considering removing this separation so that every package has the same layout, and I'd like to get your feedback before making the change.
I initially made this separation because it allowed me to put x86 and x64 in the same package, but I don't do that anymore, and the subfolders are causing me troubles with CMake where there is no reliable way to detect the target CPU architecture (bblanchon/pdfium-binaries#17).

Please let me know if changing the Windows packages layout is a problem for you and if you think this is going in the right direction or not.

Best regards,
Benoit

**Comment by mara004** [comment]
Hi,

First of all, many thanks for your report, and for hosting `pdfium-binaries`.

Yes, I noticed these differences in the Windows binaries, and already wondered about them when implementing the corresponding passage in `update.py`. Feel free to change the layout so it is in line with the other packages. I would even appreciate this change.

If you are done, it would be nice if you could leave a short comment, and I will adapt the script accordingly (or you may also submit a PR if you like).

Kind regards

**Comment by mara004** [comment]
Related code:

https://github.com/pypdfium2-team/pypdfium2/blob/f41831c89b43a1f1462c25a8dbb4fb8ad32e1199/update.py#L186-L202

**Comment by bblanchon** [comment]
I just pushed the change; next Monday's build will have the new layout.

**Comment by mara004** [comment]
Thanks, I plan to create a branch to change the update file and will merge it into main when the next build arrives.
